# Generated by Django 4.2.4 on 2023-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_engaged",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Started Working"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date Of Birth"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
