# Generated by Django 4.2.4 on 2023-08-06 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(auto_now=True)),
                ("task_name", models.CharField(max_length=255)),
                ("task_description", models.TextField()),
                ("complete", models.BooleanField(default=False)),
                ("other_explanation", models.TextField()),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tasks",
            },
        ),
    ]
